Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: main
      CodeUri: /Users/shawn/workspace/intellilead/code-workspace/ReviewHandlers/src/cmd/lineEventsHandler
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STAGE: local
          AUTH_REDIRECT_URL_PARAMETER_NAME: /auth/authRedirectUrl
