Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: sendReviewToUser
      CodeUri: /Users/shawn/workspace/intellilead/code-workspace/ReviewHandlers/script
      Runtime: go1.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          STAGE: local


